fullnameOverride: ingress-nginx-internal
controller:
  service:
    annotations:
      lbipam.cilium.io/ips: 192.168.1.32
    externalTrafficPolicy: Cluster
  ingressClassResource:
    name: internal
    default: true
    controllerValue: k8s.io/internal
  admissionWebhooks:
    objectSelector:
      matchExpressions:
        - key: ingress-class
          operator: In
          values:
            - internal
  config:
    allow-snippet-annotations: true
    annotations-risk-level: Critical
    # taken from https://github.com/ai-robots-txt/ai.robots.txt
    block-user-agents: AdsBot-Google,Amazonbot,anthropic-ai,Applebot-Extended,Bytespider,CCBot,ChatGPT-User,ClaudeBot,Claude-Web,cohere-ai,Diffbot,FacebookBot,FriendlyCrawler,Google-Extended,GoogleOther,GPTBot,img2dataset,omgili,omgilibot,peer39_crawler,peer39_crawler/1.0,PerplexityBot,YouBot,
    client-body-buffer-size: 100M
    client-body-timeout: 120
    client-header-timeout: 120
    enable-brotli: "true"
    enable-ocsp: "true"
    enable-real-ip: "true"
    force-ssl-redirect: "true"
    hide-headers: Server,X-Powered-By
    hsts-max-age: 31449600
    keep-alive-requests: 10000
    keep-alive: 120
    log-format-escape-json: "true"
    log-format-upstream: |
      {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}
    proxy-body-size: 0
    proxy-buffer-size: 16k
    ssl-protocols: TLSv1.3 TLSv1.2
    use-forwarded-headers: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespaceSelector:
        any: true
  extraArgs:
    default-ssl-certificate: network/zeinfahrozi-my-id-staging-tls
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 500Mi
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUGp4R0NtYkpNNHNqYm9a
        ZkxYY1pkVEh4eG1TRHZ4MGpSTXNrejJTMVdNCklwMzd2RkFLbkY3VG43K3luSlNw
        RzF1ZEgxNUliSEdadmhoQkRFSXhhNVUKLS0tIDUwUFVkanpwY3AxWGNXLzZVQW1Y
        L0pNUmpCK254UGo2TkJyTThMYWtDS0EK3SQG9ljgFVn0Ff+tObbmMpQa5FNf+I4m
        dMLdzOEhhl3nCqF0N7kNIi8gs3he+n9gNgYfZxT+QPGe+aR9zF7iYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:52Z"
  mac: ENC[AES256_GCM,data:O9kE0Rwy1+atf3ftgKGyutde4u3EejnMNbJIDEGgweKSucwryLqICFqd29gETsUpZMy4EpxwAvLVKRspX4VBBvM/Vyve+KB3C41oHri/RvgDBVib0Ok82BwHDsvhoKjVMbL1ppSOhFMsvZdAhDBWGeXAYOl1GKxh33Mi0Q01GfQ=,iv:Vnv6VVF4b6tw6CkdsqYwo872cbsY3Co2koSOfh+AxqQ=,tag:ZDNw+sjS4FaSvUVzvRvajA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
