# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeinfahrozi-my-id-staging
spec:
  secretName: zeinfahrozi-my-id-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: zeinfahrozi.my.id
  dnsNames:
    - zeinfahrozi.my.id
    - '*.zeinfahrozi.my.id'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYTdnSEI1ZFF0SHZKVW1F
        ZnpXUjk5c0hTcGNaelR3YXFkR3RyeG80MWlnCjhXcDBGMkVsbnhxYjJRMmJaeklm
        RThxaTlFVzNXUjdERmxHSlR3YnhEa00KLS0tICttRWVWaXR0NW4zNHRFVWVYS3VX
        VW5oNi94OEo0dHc1Z01xbDJGWVppaGcKmcVTZr57DLpNDnK4QVMja9/xjKnXPikD
        /PKBL6YyII3XIMra6ugS52VKGiWSHMkBoVDX53S1wvHmWLjpAHOTDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T13:13:49Z"
  mac: ENC[AES256_GCM,data:i/h7Uvqp83Yla2LbzFegDrBveQEyq+u7LPmWXp+mgQ5fZAEzZ6my++e0tXnu+AX4bThRDzPK+fQX+5DNQc21v7f4cVJQbCui2DdkdKplSBXFdBAsVfKTZcrR7ZFz+4wGzJmpxbAjCrT/dR6rXPUjRFKsLcfClpq5eKVyJkAKNdE=,iv:QXNMi0Joc2WaxG9dHBE5gXu/4bKj1RuY51cbFKSOzuI=,tag:hHOuWlnZ7wQlm0DF6Z26VQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
