# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeinfahrozi-my-id-staging
spec:
  secretName: zeinfahrozi-my-id-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: zeinfahrozi.my.id
  dnsNames:
    - zeinfahrozi.my.id
    - '*.zeinfahrozi.my.id'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVE5IV0g1Nk1UZlpjMmNW
        bHczVk5iY2d4b2tHOGR6ZmdIVTcyKzcwN25RCkhjSTRsdG9HYXpIWExyM1VzWEdZ
        MGhMY1ZlOEdNejVHZndRcm1aQ2d5UkUKLS0tICs5ZHhJN0N3Wk5MZDZ0eTI4WHNl
        OWovQzZqQ0RYNnU2ejY3YitWdkMrU28K8Oi9sGPGLKh8anTUzu9Wqf2QI8d228j+
        a2hJNsHxbms9EBw40xMSxfeOJJwWRf0Tp4suUZJyOGqCG9q3tk0cew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:53Z"
  mac: ENC[AES256_GCM,data:kiLhBco3e0M8yadSXK1rW7rNqKkBJCAhGtXtKsHgw8WNU59AGXXald83nBioHTSqg2VWiYmPPiNxRbzexUOHhM6oQ1bZAc9sQIOu/0f4pO/YwRcq5Kih9saWiwRmeAmGgC8/hL2GB58ENGAJ49W4UmD1fdOtc7iS5JUSQ1AMlHA=,iv:+Sf8Xj1CCoqUJHVjzGTAOM8b17uegT59V/LUKFvJttM=,tag:FCsvD4xFxUzgkKA8Y2Numw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
