# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:yb/K,iv:BYtN2/lq6uXwEok6nanOzStCiH6fvBAyPyXV5twOiRo=,tag:lGEJ5jxdfieByI7U4AlbuQ==,type:str]
  url: ENC[AES256_GCM,data:Drisgk5ZBvk3Y85JrKL6GyqURU04n+YVzkU4HD8LgLVM/S4J5CxOHS/2IPatCEf+,iv:XIoJEfk4PruiVVKp+J4h/nTBLN+psY+p4L2MRT5iceQ=,tag:Hy4kGtWq8rwRQbB8TbKeyw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZURJUXdObVRiaVJ3V2c2
        d2tPME9wUzNwd0xrQ0o2cmtDN3pXeWxVWldnCmFUOHRTRk8rUFFyTDQ0WUxFUG1T
        c0Jjbk0rVVlGWWVyNXF0OHhCN3VVRk0KLS0tIHI3ZmRDK2JxM3F6YTVBQ3BkRE9j
        VDRkWFowdTdVaktQOGxPWHR4QVZpRDgK5apNP/Eh6ePn2SgdJ3weHjjVqASturoz
        z7SxmOOjoY2kbUEXJUiLg93+0V3MOxZdVLuMXrb9pyAcpVINCWPHGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:51Z"
  mac: ENC[AES256_GCM,data:AI2Q6fng9QKavgb8TWG4SXviV1zyDSdgtTHZSPioHCDzjzA46kmJ/30CafMkeQ5kfKJph4o5pFJNryu3julsiMVKZQv/qsyZf9tV1BwnJtY9z2coXncv9pM0+sU8Lh+DewA/058PB22dDEfQMzKFmk46sCJiw3BQ1m5KuJluxbQ=,iv:jkTNzXpGanI0VyzLXhbtd9nW7QyC9Z/bDwmG0cUxF20=,tag:Nu5SHmRPsyDITb1kFF9GOg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
