fullnameOverride: external-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --events
  - --ignore-ingress-tls-spec
  - --ingress-class=external
policy: sync
sources:
  - crd
  - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - zeinfahrozi.my.id
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: external-dns-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVU5rYVI3NlhGOExDVmR3
        YUtqQzBqOUxhTU02YjNEY3EzOXV2ZTBuMEFZCml0d3Q2OXphTXRMdG9paGZwL0lj
        V1p6VkEydTNZYTdobmdKdllLdU83VjgKLS0tIGlXaExBZmVCVEdWQ1ZoK0dtRS81
        U1hhcUs5NzZ0UWpITitBZnUzYXFXeVEKi4XmzSELt0ZuuHVF9JE4aMT5Xcq9a0hv
        cHLdgb0aG+hXkjwKR3l8fUsjXqyQ+yUHuN+vfEwx5SwAmFK4W+nmMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:52Z"
  mac: ENC[AES256_GCM,data:VdnV1K2ingh4Qv+I3b6RwdNCienYjXv2Eep//HByA2BOd0Wy9c3DCsFpHJMAThUi7LkdcZ7E76uAK5qEJpwW5/48MLJrQ9S15srDej7VOAiAQLFPcOXzv+9w/B45T2/7B6QSS2JAiZP0rTP6sO85fLOldrpgP2fmYu+/VhDgGyE=,iv:AV31+elzpwJ0M19UvDnCxzZgQLv1Eq3ZnQizkR8hGB0=,tag:vXOagPGJ3B6IpIzEa9Gw0w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
