# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - zeinfahrozi.my.id
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdWRIb3JTQ1hMdmxRMStk
        YkczQmplSVNOM3dOdTIwRTVHZmtaWWFpV2hJCjVHOHBQOGg2NjJ5TCtVenVoSGNH
        SXM0dnhvcEZPOTBXQ283T3VZVGZMN28KLS0tIHRJdzBrZlZaOUZTaE1jNStoN0d0
        M1Rib0ZTQS8reVFueGRhWS9BMU05dTQKCLhe9O1r+ZOHafYGcZ7f2DHSLm4WAiwE
        j/NHDC8whUIva1d1D4W0LpeuBOuwV5wk4uxKQOf+7i1Gn7TY/FuQUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:52Z"
  mac: ENC[AES256_GCM,data:Zb3fDyy2bXPtJ2xCB1aG0ph2uh5lUcY0aUSwtXJkdiVvF52ahHjUYKNDwEySA5GebfeUThTFDuLudPHF5HD8Tf1GDAkYudYNMEK+RD1Nv3qRdxDu9gOEdqrA1jF+qujcX/Oo7ZuynMC74r/ZYsUr4GB8tn68nP427J3YGHo64Uw=,iv:79lEz98lijJI5hXZwg3k2wShZl+TbLYJTp6Ld1dei+0=,tag:PZRoYfDOcugPtS0xxPz/nw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - zeinfahrozi.my.id
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdWRIb3JTQ1hMdmxRMStk
        YkczQmplSVNOM3dOdTIwRTVHZmtaWWFpV2hJCjVHOHBQOGg2NjJ5TCtVenVoSGNH
        SXM0dnhvcEZPOTBXQ283T3VZVGZMN28KLS0tIHRJdzBrZlZaOUZTaE1jNStoN0d0
        M1Rib0ZTQS8reVFueGRhWS9BMU05dTQKCLhe9O1r+ZOHafYGcZ7f2DHSLm4WAiwE
        j/NHDC8whUIva1d1D4W0LpeuBOuwV5wk4uxKQOf+7i1Gn7TY/FuQUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:52Z"
  mac: ENC[AES256_GCM,data:Zb3fDyy2bXPtJ2xCB1aG0ph2uh5lUcY0aUSwtXJkdiVvF52ahHjUYKNDwEySA5GebfeUThTFDuLudPHF5HD8Tf1GDAkYudYNMEK+RD1Nv3qRdxDu9gOEdqrA1jF+qujcX/Oo7ZuynMC74r/ZYsUr4GB8tn68nP427J3YGHo64Uw=,iv:79lEz98lijJI5hXZwg3k2wShZl+TbLYJTp6Ld1dei+0=,tag:PZRoYfDOcugPtS0xxPz/nw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
