# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2I0rTTBsw6cCqnRPmrelP3bPjusbfwL+ZRSwHs/qY9ueU74p31wKVg==,iv:6dcfBBex2FibBcUXvIIUQy9B3NioP1Hi0VOfwkBRaKY=,tag:UQ67PxitSkbRtOI/METRDA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OEtpeHNhZ1ZIczQ1QkxL
        c0FxMnkrTDVXYmlwdy95TGpJQXVGOSs5ZjBVCklPM28rOEhqM3JuNWwrMG43NWYy
        SjNCUmVGRTFCRVNjZ2JVcVRxVnQ4NXMKLS0tIFJjaXJDZlFPQ1pzYjNTbGtlWEp1
        ZGVsdXZmNDJSb2JUN2pvMGxIUmZ5YW8KLCCfkvEQl6uAYtGwvLpdaXQsXklCs7aX
        fq7YKkEUqVjt3LdvVuP08wcx7l42xyq1G7ec3CDi2QwcDuZoYVpU6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T13:13:48Z"
  mac: ENC[AES256_GCM,data:/bSvzbt9alOsdOFBTrCAmkq2BI2mR2HraDawlBO+0Ow1h4Kjxgzqu6rvVgxKJ7ZA/tgYo+wY3hVQOoIdPEwL9sTZhzDErY83ushFNj0iOHqbxO014iDq1DKt6C6an2xUDJ4lvHIhigQJN4I/N5BqMTcO1/iz9WNiklgZ4tD152o=,iv:Nzax3q6rWn/G3/+qTSUdFgpaj9auwiraPYz80HwZVTg=,tag:PJVnbxc3/6/VmYj0EqSFiA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
