# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:/rN3CBuh52+TYQsRcXwHiaZi9uXoG3Lg6MkItj8hsUUM3vcWOEL31Q==,iv:vRLWvjJABWHD+K5WtlvOhoEtDEaNJ2eN7U7JxMTLZak=,tag:VEUvtesm6GpvZDnvx3J7pA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM2ZidEhWd1VqOHRLTHcy
        VWhUMWhuUldJVHFVTlpKQllXTGFVQlRhYVhFCkVSVnJSdG5UczJGOTc4R0tRUmdk
        THF4OXdEZFNKcnJuT3dIOUtzbWdiTUEKLS0tIGZUUEpXVlNKQnpaUkxuMkZjczh6
        cXVtQUNpVmFYR05iYVFNaUpPbG9uYUkKMFvrQUn6QCWSi9O5M3OgdGu/xUBZ7DcV
        V2CxbRH6Izg5ab+AvSkI16NfDIrFQcfd9es/9nQ7ntTiygQk8onqsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:51Z"
  mac: ENC[AES256_GCM,data:h24DmcSC17hWWx/dI2rb2DiqGlqNu6Wt8xSXaZpHHBXinQa+tEZyu++WOjsb0Rrhho7KUyvg49W7UYPDzit9gspl9BZ5I6Hekngqrvh73XSiTP9ugB3IANSXepzh13nZLRgUDsQ9PVz/aQNtTZu8or7NI/ohweEotmgIIONuCTE=,iv:6UFyoNYIpUVOxXU/TnPTEXmIFwwsSvDuP3M8vVdjk/o=,tag:4ygt9+PJJLbMOBZcD/Z/jQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
