apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:puFQD5SgNnxxjnyV3bLyp9RYQ1xsOdcwk7KJKhI3fAofmFbkYC2fQg==,iv:O96W7S9l+uvdCoyk2LIE9ls4XB0vMSyGOssK7ujO3Rg=,tag:V8j/OhiNEv4k+Vnl+y/grg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U2wrUVBwN3ZQZDJVc3p5
        Unc0T3JSNFhOdVdDcjZoWHlsZVBGYXQ3WGc4CjFGVHl5cGVFbVpkNkh0NkxPaEhq
        NlZndHUxQ1ZHSy9zZkdmNUh4aU03a1EKLS0tIGVzQTdHQVBLRWtGUTJ3SnRqV05H
        eXV4aXZCZzQxTWxXWTdwcjV5cDJtMWMKLFO4gbWuY8mGmta/Uk9NSeL+edO5sc9U
        cHgJvt3emgXbRf8FCPaSnxEbTfSX3P3NhNB8ZiU+arN/r8oPkZiFiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T13:13:48Z"
  mac: ENC[AES256_GCM,data:bU1mZZ7AEyhYusR995X5HekErBMivZckiysw2hd8kbH0thg2J5ar+e8tQkoEAvkGQweoliOvk+hi0Z6GZ+/1D4Ki0/Z28VHFNRF2AFJF4KIV8BJuJZicDXwkutERb7TuaZU+SxOF3wvW6bzB4PnK37dfBxhGI9LXHNOKWrspH1o=,iv:dgxAkVRr65cdm6BD7Nf4CrRmlvQUuRcA8vewH1c3Br8=,tag:BEH6I4Yx0Ty8+A1ly9cV7w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
