apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:ZcseIavZ0AGb5jpOHq8b+n4bfPkyE3Ra/TcCIvRVlh3RWTKk4sX4Mb2LogXfC7MoGRz6TqiL35bHi3TUDbZCdKOBvGhczdSak1Wa,iv:uJf4RoT8DD3jkczJfkawdwtWt0gmfc9JpXdezLn2In0=,tag:lc/TXrVaVOpuDWmg0OM0aw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q1A2RkZ1emdVZWxoSWlM
        R1FuRjNVbTI0WjFMU2d3SFRKVitpcjVRc2xBCmFBU1RBeU5XNjJMMVVZNEc3bHlL
        dEQ4NEpqMC9xTUFIR0RoZmNJTmRXclEKLS0tIHE0ZUVVY0ROWjNtemtqZGlRdGNN
        LzRsRlBFVDBjakk3bjVqWTNQYnNGQTQK/FREyIrJqh4+L3tScjlAjZX4N40s87PS
        tbBZeWeUgsfTpP8L3QauuGOn8nStFIOjDNkmrMupdQbSMBjaDVoXWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:51Z"
  mac: ENC[AES256_GCM,data:BQhWWbaFsCjdV+Er/Y9YgzKNMt6zSqpLb9210mFAuvLVIz5U9r/28m4LrFuo22M2vQAcu9DburKrz/exoHd3ehL2awLlGY0iggOHEKsYnxQgL6z4x5fhIJjE9txdbDbyfBWcWZ2EVXMWLb7tggc+uB0SIyZVQinb7wlvifcmJig=,iv:Kiwig6dd2UDVWMUYsaE0/t3kFe6Ifw+wJJsrkZgOLnA=,tag:a9FfHMRCOY7/h43UPR9Pow==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
