fullnameOverride: k8s-gateway
domain: zeinfahrozi.my.id
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.27
  externalTrafficPolicy: Cluster
watchedResources:
  - Ingress
  - Service
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc3dxY2hDL1pKNTlKL0xK
        NlcwL2pSMEZ5M3V0L3pYRHJlWE9vWnZaeVNBCnRRR3gvcUJ5VExZQjFFVnRIcmQ0
        dTRldTRRTzRmVUxFbEFLSk42OXp0bkEKLS0tIFFoc01GK0xzaGtaemlsb1UxQTZv
        bGwvOGRnQ1o5RTV1aEZVSTZpaFFiUTQKGq69FpMFyMyccuzTtLtxRjP+VDQsZuim
        uS6mrY5ua+Z3WuSl0I7p/Umf4fP/OACs6/o+mH0V/C9tdYNaV5ACYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T13:13:48Z"
  mac: ENC[AES256_GCM,data:+Lq41bXHZ0PJjHiTbT2W7ekg6GV3Qh2O2zQRt9xu/bopSK0gAPaQUNIE3aLbBHG0a7uPiZydQ5mI2b7u30QjS25/eCbhFejNqXvPCKO7pF/h4YMOffCwEzREExJGSwfzDp3P1yxuMYyUi4HxzXsJzxPypwYWUOpxI+EgKcwczOU=,iv:JLoTtCAf33lkPSxMtGe7DtgBTeRLtV/CbR2dsBSlPAg=,tag:vVVD4O430dinTV93yzJ7/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
