fullnameOverride: k8s-gateway
domain: zeinfahrozi.my.id
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.31
  externalTrafficPolicy: Cluster
watchedResources:
  - Ingress
  - Service
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1az3egsktxq4y33wltcll3ltk88a53j39g5zevmcgth4hs6p38vhs5j8kyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS1V5T1F0S3REOVQyT0lp
        SEkyUXg4OVNSM0RBTmFnRldselh3dVFobGpvCjVFTzRFMFo4K3NpN0RZZmpDU3VU
        RTZVMEZ2dlVaWTQ3YzN4dWJDNGFZcEkKLS0tIHlOOVBSZnlGWkpER2Nva2tNUi9Z
        ZnJiQ3BHRitnWStlemo5LzJ2Z2gzNHMKb0K6heZJd4ry8ocpTLBbJkghkaZZ8vzO
        w+IwY4E7QxlmB8Ez5hv1z+8N9khvG4jI6/hTEfgEZB4T9gtMLQCQ6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T16:35:52Z"
  mac: ENC[AES256_GCM,data:qtlxbnXVh6QCmEXCh51pd6eziCIvqeDxQw0XJBxDCEvAaTmq7uu94oFZt2ts6/8b4NHTBQu3x1nsqUHVX3Le3/k9mzNC5VlA4h/Oxymk+uYY3s2gsDitdR8U1ZmEad23RIjkBd26BZznzyL8O215twLzLnQBLEe22TzoI8S5KLk=,iv:NCk68bN53OqYlwDPN9ZnqGivrSXg6r7e8WAz7EiPA3U=,tag:S7qlBGWk54jPF8AkJc+CIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
